# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "BOySKarfB7ySP4SQ9vpeLz/Yrle3cxGYe+f5ep6OVk42M2bmonX27FdgVF5oKpII6Sq5hXrhoNrwRpkYRj+G5OUy4lguOALJ1AAtRpvlrfXCCL5Vxe9TDBNpmU/AfOcZoiGiR5Vpv96CIIoqvnB6XQJMMfTa2JHvU7tZCS2p9lU="

addons:
  coverity_scan:
    project:
      name: "troglobit/smcroute"
      description: "SMCRoute -- Static Multicast Routing Daemon"
    notification_email: troglobit@gmail.com
    build_command_prepend: ./autogen.sh && ./configure
    build_command: make -j5 clean all
    branch_pattern: dev

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
script:
  - ./autogen.sh
  - ./configure --disable-silent-rules --prefix=
  - make clean
  - make -j5
  - make
