# Travis CI integration
language: c
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ozYzmWMFbneep0nRVwFGBAds7v7NK6iDbFczqY4ZJXKaSU16MAN6g/WxaRYdRyTrhzb6kUfwgRyajvRV48npb62ohl9/mbSYibCSpL76ZYwEtqOPK7lOCz0/c6KyT3ItPlM508K2EG/UdU+M+nbc54ZpvyuZeaDDW6vCxbfKZqQ="

addons:
  coverity_scan:
    project:
      name: "troglobit/smcroute"
      description: "SMCRoute -- Static Multicast Routing Daemon"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./configure"
    build_command:   "make -j5"
    branch_pattern: master

script: ./configure && make -j5
